name: quizzly_math
description: This is Quiz App In Math

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  confetti: ^0.8.0
  circle_flags: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  generate: true
  assets:
   - assets/images/

  fonts:
   - family: DMSans
     fonts:
       - asset: assets/fonts/dms_ans/DMSans-Bold.ttf
         weight: 700
       - asset: assets/fonts/dms_ans/DMSans-Medium.ttf
         weight: 500
       - asset: assets/fonts/dms_ans/DMSans-Regular.ttf
         weight: 400
         style: normal
   - family: ExpletusSans
     fonts:
       - asset: assets/fonts/expletus_sans/ExpletusSans-Regular.ttf
         weight: 400
         style: normal
