name: quizzly
description: This is Quiz App In Math

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #  For Animation Confetti
  confetti: ^0.7.0
  # For Country Flags
  circle_flags: ^1.0.4
  # For Save Memory
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # For Languages Localizations
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true
  assets:
   - assets/images/

  fonts:
   - family: DMSans
     fonts:
       - asset: assets/fonts/dms_ans/DMSans-Bold.ttf
         weight: 700
       - asset: assets/fonts/dms_ans/DMSans-Medium.ttf
         weight: 500
       - asset: assets/fonts/dms_ans/DMSans-Regular.ttf
         weight: 400
         style: normal
   - family: ExpletusSans
     fonts:
       - asset: assets/fonts/expletus_sans/ExpletusSans-Regular.ttf
         weight: 400
         style: normal
