name: quizzly
description: This is Quiz App In Math

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true
  assets:
   - assets/images/

  fonts:
   - family: DMSans
     fonts:
       - asset: assets/fonts/dms_ans/DMSans-Bold.ttf
         weight: 700
       - asset: assets/fonts/dms_ans/DMSans-Medium.ttf
         weight: 500
       - asset: assets/fonts/dms_ans/DMSans-Regular.ttf
         weight: 400
         style: normal
   - family: ExpletusSans
     fonts:
       - asset: assets/fonts/expletus_sans/ExpletusSans-Regular.ttf
         weight: 400
         style: normal
